### ISSUE TITLE
is fftset faster than nnpack?

### ISSUE THREAD

**Issue by outgrid** [nickappleton/fftset#1]

**Comment by nickappleton** [comment]
Hi!

I've had a look at the [NNPACK API](https://github.com/Maratyszcza/NNPACK/blob/master/include/nnpack.h) and I suspect that it so-greatly differs from fftset in both use-cases and features that I don't think they are comparable. NNPACK is an "acceleration package for neural network computations" (something I know close-to-nothing about) while fftset is designed for performing strictly one-dimension convolutions. fftset does not support multi-dimensional data sets (which NNPACK appears to do) and is based on a mixed-radix and multi-pass implementation. It does not support more interesting (/prime) length DFTs. fftset targets the C90 abstract machine (with extensions when they can be detected) and also supports building on Windows with Microsoft toolchains which NNPACK does not support.

If the use of NNPACK was restricted to the use-case of evaluating single dimension convolutions (which I think it **can** do - but probably was not designed for), there would be some work in creating a profiling harness to figure out which library is faster. This is not something I'm willing to do as part of this project at the moment.

Thanks,

Nick

**Comment by outgrid** [comment]
thank you very much! hopping support multi-dimensional data in the future
